# Generated by Django 3.2.19 on 2023-07-18 18:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='created_at',
        ),
        migrations.AddField(
            model_name='link',
            name='links_url',
            field=models.URLField(default=datetime.datetime(2023, 7, 18, 18, 21, 36, 785456, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
