# Generated by Django 3.2.19 on 2023-07-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20230718_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='links_url',
        ),
        migrations.AddField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(default='2023-07-27 12:00:00'),
        ),
        migrations.AlterField(
            model_name='link',
            name='shortened_url',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
